<?php
    /**
     * Created by PhpStorm.
     * User: 阳毅
     * Date: 2018/7/4
     * Time: 11:17
     */

    namespace app\index\controller;


    use think\Controller;

    class Common extends Controller
    {
        protected $confs;

        public function _initialize()
        {
            parent::_initialize(); // TODO: Change the autogenerated stub
            $this->nivo();
            $this->relevant();
            $this->recent();
            $this->conf();
        }

        private function nivo ()
        {
            $nivo=db('article')->order('id desc ')->paginate($this->conf()['rj'],false);
            $this->assign('nivo',$nivo);
        }
        private function relevant ()
        {
            $relevant=db('article')->order('id asc ')->paginate($this->conf()['rx'],false);
            $this->assign('relevant',$relevant);
        }

        private function recent ()
        {
            $recent=db('article')->order('id desc ')->paginate(3,false);
            $this->assign('recent',$recent);
        }
        private function conf ()
        {
            $conf=db('conf')->find(1);
            $this->confs=$conf;
            $conf['background']=str_replace('\\','/',$conf['background']);
            $this->assign('conf',$conf);
            return $conf;
        }

    }